services:
  web:
    image: php:7.4-apache
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
    command: >
      sh -c "docker-php-ext-install mysqli && apache2-foreground"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
