version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - my.env
    depends_on:
      - db

  db:
    image: postgres:13
    env_file:
      - my.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
     test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
     interval: 10s
     timeout: 5s
     retries: 5

volumes:
  pgdata:

