version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - my.env
    depends_on:
      - db

  db:
    image: postgres:13
    env_file:
      - my.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: ["sh", "-c", "printenv && docker-entrypoint.sh postgres"]

volumes:
  pgdata:

